//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emanuel.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Church
    {
        public int ChurchId { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public int ZoneId { get; set; }
        public int PastorId { get; set; }
    
        public virtual Pastor Pastor { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
