//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emanuel.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.Meeting_Pastor = new HashSet<Meeting_Pastor>();
        }
    
        public int MeetingId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime StarMeetingDate { get; set; }
        public System.DateTime EndMeetingDate { get; set; }
        public int MeetingTypeId { get; set; }
    
        public virtual MeetingType MeetingType { get; set; }
        public virtual ICollection<Meeting_Pastor> Meeting_Pastor { get; set; }
    }
}
