//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emanuel.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinisteralLevel
    {
        public MinisteralLevel()
        {
            this.Pastors = new HashSet<Pastor>();
        }
    
        public int MinisteralLevelId { get; set; }
        public string MinisteralLevel1 { get; set; }
    
        public virtual ICollection<Pastor> Pastors { get; set; }
    }
}
