//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emanuel.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pastor
    {
        public Pastor()
        {
            this.Churches = new HashSet<Church>();
            this.Meeting_Pastor = new HashSet<Meeting_Pastor>();
        }
    
        public int PastorId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public int Code { get; set; }
        public string CellNumber { get; set; }
        public System.DateTime PresentationDate { get; set; }
        public int MaritalStatusId { get; set; }
        public int MinisteralLevelId { get; set; }
    
        public virtual ICollection<Church> Churches { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual ICollection<Meeting_Pastor> Meeting_Pastor { get; set; }
        public virtual MinisteralLevel MinisteralLevel { get; set; }
    }
}
