//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emanuel.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.Churches = new HashSet<Church>();
        }
    
        public int ZoneId { get; set; }
        public int ZoneNumber { get; set; }
    
        public virtual ICollection<Church> Churches { get; set; }
    }
}
